// ------------------------- POPULATION ------------------------------------ //

export const FETCH_POPULATIONS = 'FETCH_POPULATIONS';
export const FETCH_POPULATIONS_FULFILLED = 'FETCH_POPULATIONS_FULFILLED';
export const FETCH_POPULATIONS_RESOLVED = 'FETCH_POPULATIONS_RESOLVED';
export const SELECT_POPULATION = 'SELECT_POPULATION';
export const UNSELECT_POPULATION = 'UNSELECT_POPULATION';
export const CHANGE_POPULATION_SELECTOR_TYPE = 'CHANGE_POPULATION_SELECTOR_TYPE';

// ------------------------- HUDDLE ---------------------------------------- //

export const REQUEST_CARE_TEAMS = 'REQUEST_CARE_TEAMS';
export const RECEIVE_CARE_TEAMS = 'RECEIVE_CARE_TEAMS';
export const SELECT_CARE_TEAM = 'SELECT_CARE_TEAM';
export const REQUEST_HUDDLES = 'REQUEST_HUDDLES';
export const RECEIVE_HUDDLES = 'RECEIVE_HUDDLES';
export const SELECT_HUDDLE = 'SELECT_HUDDLE';
// export const ADD_PATIENT_TO_HUDDLE = 'ADD_PATIENT_TO_HUDDLE';

// ------------------------- RISK SERVICE/ASSESSMENT ----------------------- //

export const FETCH_RISK_SERVICES = 'FETCH_RISK_SERVICES';
export const FETCH_RISK_SERVICES_FULFILLED = 'FETCH_RISK_SERVICES_FULFILLED';
export const FETCH_RISK_SERVICES_RESOLVED = 'FETCH_RISK_SERVICES_RESOLVED';
export const FETCH_RISK_ASSESSMENTS = 'FETCH_RISK_ASSESSMENTS';
export const FETCH_RISK_ASSESSMENTS_FULFILLED = 'FETCH_RISK_ASSESSMENTS_FULFILLED';
export const FETCH_RISK_ASSESSMENTS_RESOLVED = 'FETCH_RISK_ASSESSMENTS_RESOLVED';
export const SELECT_RISK_SERVICE = 'SELECT_RISK_SERVICE';
export const SELECT_RISK_ASSESSMENT = 'SELECT_RISK_ASSESSMENT';
export const FETCH_RISK_ASSESSMENT_BREAKDOWN = 'FETCH_RISK_ASSESSMENT_BREAKDOWN';
export const FETCH_RISK_ASSESSMENT_BREAKDOWN_FULFILLED = 'FETCH_RISK_ASSESSMENT_BREAKDOWN_FULFILLED';

// ------------------------- PATIENT --------------------------------------- //

export const FETCH_PATIENTS = 'FETCH_PATIENTS';
export const FETCH_PATIENTS_FULFILLED = 'FETCH_PATIENTS_FULFILLED';
export const FETCH_PATIENTS_RESOLVED = 'FETCH_PATIENTS_RESOLVED';
export const SET_PATIENT_SEARCH = 'SET_PATIENT_SEARCH';
export const SELECT_PAGE = 'SELECT_PAGE';
export const FETCH_PATIENT = 'FETCH_PATIENT';
export const FETCH_PATIENT_FULFILLED = 'FETCH_PATIENT_FULFILLED';
export const FETCH_PATIENT_RESOLVED = 'FETCH_PATIENT_RESOLVED';


// ------------------------- SORT ------------------------------------------ //

export const SELECT_SORT_OPTION = 'SELECT_SORT_OPTION';
export const SET_SORT_ASCENDING = 'SET_SORT_ASCENDING';
