// ------------------------- POPULATION ------------------------------------ //

export const FETCH_POPULATIONS = 'FETCH_POPULATIONS';
export const FETCH_POPULATIONS_FULFILLED = 'FETCH_POPULATIONS_FULFILLED';
export const FETCH_POPULATIONS_RESOLVED = 'FETCH_POPULATIONS_RESOLVED';
export const SELECT_POPULATION = 'SELECT_POPULATION';
export const UNSELECT_POPULATION = 'UNSELECT_POPULATION';
export const CHANGE_POPULATION_SELECTOR_TYPE = 'CHANGE_POPULATION_SELECTOR_TYPE';

// ------------------------- HUDDLE ---------------------------------------- //

export const FETCH_HUDDLES = 'FETCH_HUDDLES';
export const FETCH_HUDDLES_FULFILLED = 'FETCH_HUDDLES_FULFILLED';
export const FETCH_HUDDLES_RESOLVED = 'FETCH_HUDDLES_RESOLVED';
export const SELECT_HUDDLE_GROUP = 'SELECT_HUDDLE_GROUP';
export const SELECT_HUDDLE = 'SELECT_HUDDLE';
